var repository = [ /* Pokedex Object Array*/
  {
      name:'Squirtle',
      height:0.5,
      type:['water']
  },
  {
      name:'Butterfree',
      height:1.1,
      type:['bug','flying']
  },
  {
      name:'Pikachu',
      height:1.04,
      type:['electric']
  },
  {
      name:'Ninetales',
      height:1.1,
      type:['fire']
  },
];
